//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Northwind.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accesss
    {
        public string UserName { get; set; }
        public string Passwword { get; set; }
    }
}
